AdminPanel/Controllers/CategoryController.cs
using AdminPanel.Models;
using AdminPanel.Repository.Interfaces;
using AdminPanel.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AdminPanel.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Categories()
        {
            return View(_categoryService.GetAll());
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Category category)
        {
            _categoryService.Add(category);

            return RedirectToAction("Categories");
        }

        [HttpPost]
        public IActionResult Delete(int id) 
        { 
            _categoryService.Remove(_categoryService.GetById(id));

            return RedirectToAction("Categories");
        }

        public IActionResult Update(int id)
        {
            return View(_categoryService.GetById(id));
        }

        [HttpPost]
        public IActionResult Update(Category category)
        {

            _categoryService.Update(category);

            return RedirectToAction("Categories");
        }

    }
}

AdminPanel/Controllers/OrderController.cs
using AdminPanel.Models;
using AdminPanel.Repository.Interfaces;
using AdminPanel.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Telegram.Bot;

namespace AdminPanel.Controllers
{
    public class OrderController : Controller
    {
        private IOrderService _orderService;
      

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public IActionResult Index(Dictionary<string,string> filter)
        {
           
            return View(_orderService.GetAll(filter));
        }

        public IActionResult BasketDetails(int id) 
        {
            return View(_orderService.ReturnBasket(id));
        }

        public IActionResult Update(int id)
        {
            return View(_orderService.GetById(id));
        }

        [HttpPost]
        public IActionResult Update(Order order) 
        { 
            _orderService.Update(order);

            return RedirectToAction("Index");
        }
    }
}

AdminPanel/Controllers/ProductController.cs
using AdminPanel.Models;
using AdminPanel.Repository.Interfaces;
using AdminPanel.Repository.Repository;
using AdminPanel.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace AdminPanel.Controllers
{
    public class ProductController : Controller
    {
      
        private IProductService _productService;
        private ICategoryService _categoryService;
        public ProductController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        public IActionResult Products()
        {
            return View(_productService.GetAll());
        }

        public IActionResult Add() 
        {
            ViewBag.Categories = _categoryService.GetAll();
            return View();
        }

        [HttpPost]
        public IActionResult Add(Product product) 
        { 
            _productService.Add(product);
           
            return RedirectToAction("Products");
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            _productService.Remove(_productService.GetById(id));

            return RedirectToAction("Products");
        }

        public IActionResult Update(int id)
        {
            ViewBag.Categories = _categoryService.GetAll();
            return View(_productService.GetById(id));
        }

        [HttpPost]
        public IActionResult Update(Product product)
        {
            
            _productService.Update(product);

            return RedirectToAction("Products");
        }
    }
}

AdminPanel/Controllers/UserController.cs
using AdminPanel.Repository.Interfaces;
using AdminPanel.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AdminPanel.Controllers
{
    public class UserController : Controller
    {
        private IUserService _userRepository;

        public UserController(IUserService userRepository) 
        { 
            _userRepository = userRepository;
        }

        public IActionResult Users()
        {
            return View(_userRepository.GetAll());
        }

        [HttpPost]
        public IActionResult DeleteUser(int id)
        {
            _userRepository.DeleteUser(_userRepository.GetById(id));

            return RedirectToAction("Index");
        } 
    }
}

AdminPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminPanel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/jquery.datetimepicker.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/main.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AdminPanel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-dark" asp-area="">@User.Identity.Name</a>
                            }
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="maindiv">
    <div class="widget">
  <h3 class="widget-title">Категории</h3>
  <ul class="widget-list">
    <li><a asp-action="Users" asp-controller="User">Пользователи</a></li>
    <li><a asp-action="Products" asp-controller="Product">Продукты</a></li>
    <li><a asp-action="Categories" asp-controller="Category">Категории</a></li>
    <li><a asp-action="Index" asp-controller="Property">Тип характеристик</a></li>
    <li><a asp-action="Index" asp-controller="Order">Заказы</a></li>
    <li><a asp-action="Add" asp-controller="Product">Добавить товар</a></li>
    <li><a asp-action="Add" asp-controller="Category">Добавить категорию</a></li>
    <li><a asp-action="Add" asp-controller="Property">Добавить тип характеристики</a></li>
    <li><a asp-action="Add" asp-controller="ProductAddress">Добавить регион доставки</a></li>
  </ul>
</div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
   </div>
  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery.datetimepicker.full.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>