AdminPanel/Models/Property.cs
namespace AdminPanel.Models
{
    public class Property
    {
        public int Id { get; set; }

        public string Value { get; set; }
    }
}

AdminPanel/Controllers/PropertyController.cs
using AdminPanel.Models;
using AdminPanel.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AdminPanel.Controllers
{
    public class PropertyController : Controller
    {
        private IPropertyService _propertyService;

        public PropertyController(IPropertyService propertyService)
        {
            _propertyService = propertyService;
        }

        public IActionResult Index()
        {
            return View(_propertyService.GetAll());
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Property property) 
        { 
            _propertyService.Add(property);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id) 
        { 
            _propertyService.Remove(_propertyService.GetById(id));

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            return View(_propertyService.GetById(id));
        }

        [HttpPost]
        public IActionResult Update(Property property) 
        { 
            _propertyService.Update(property);

            return RedirectToAction("Index");
        }
    }
}

AdminPanel/Views/Property/Add.cshtml
@model Property
@{
    ViewData["Title"] = "Добавление типа характеристики";
}
<form asp-action="Add" asp-controller="Property" method="post">
    <div class="form-group">
        <label asp-for="Value">Введите имя для типа характеристки</label>
        <input type="text" asp-for="Value" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Добавить</button>
</form>

AdminPanel/Views/Property/Index.cshtml
@model List<Property>
@{
    ViewData["Title"] = "Тип характеристик";
}
<table class="table table-striped">
    <thead>
        <tr>
            
            <th scope="col">Название</th>
            <th scope="col">#</th>
            <th scope="col">#</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr scope="row">
              
                <td>@item.Value </td>
                <td>
                    <form method="post" asp-action="Delete" asp-controller="Property" asp-route-id="@item.Id">
                        <button class="btn btn-primary">Удалить</button>
                    </form>
                </td>
                <td>
                    <a class="btn btn-primary" asp-action="Update" asp-controller="Property" asp-route-id="@item.Id">Изменить</a>
                </td>
            </tr>
        }
    </tbody>
</table>

AdminPanel/Views/Property/Update.cshtml
@model Property
@{
    ViewData["Title"] = "Изменение типа характеристики";
}
<form asp-action="Update" asp-controller="Property" method="post">
    <div class="form-group">
        <label asp-for="Value">Введите имя для типа характеристки</label>
        <input type="text" asp-for="Value" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Изменить</button>
</form>