AdminPanel/Models/Product.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdminPanel.Models
{
    public class Product
    {
        public int Id { get; set; }

        public int BarCode { get; set; }

        public string Name { get; set; }

        public string Image { get; set; }

        public int PriceIncome { get; set; }

        public int PriceOutCome { get; set; }

        public string ShortDesc { get; set; }

        public string LongDesc { get; set; }

        public int CategoryId { get; set; }

        public int Count { get; set; }

        public int StockId { get; set; }

        [NotMapped]
        public IFormFile CoverPhoto { get; set; }

    }
}

AdminPanel/Controllers/ProductAddressController.cs
using AdminPanel.Models;
using AdminPanel.Repository.Interfaces;
using AdminPanel.Service.Interfaces;
using AdminPanel.Service.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace AdminPanel.Controllers
{
    public class ProductAddressController : Controller
    {

        private IProductService _productService;
        private IProductAddressService _productAddressService;
        private IRegionService _regionService;

        public ProductAddressController(IProductService productService, IProductAddressService productAddressService, 
            IRegionService regionService)
        {
            _productService = productService;
            _productAddressService = productAddressService;
            _regionService = regionService;
        }

        public IActionResult Add()
        {
            ViewBag.Products = _productService.GetAll();
            ViewBag.Region = _regionService.GetAll();   
            return View();
        }

        [HttpPost]
        public IActionResult Add(ProductAddress productAddress, List<int> list) 
        {
            _productAddressService.Add(productAddress, list);
            return RedirectToAction("Products", "Product");
        }

        //TODO: Доделать select в update.cs
        public IActionResult Update(int id)
        {
            var list = _productAddressService.GetAll().Where(x => x.ProductId == id).ToList();
           
            ViewBag.AllReg = _regionService.GetAll();
            return View(list);
        }

        [HttpPost]
        public IActionResult Update(List<ProductAddress> list) 
        {
            _productAddressService.Update(list);
            return RedirectToAction("Products", "Product");
        }

        public IActionResult Delete(int id)
        {
            _productAddressService.Remove(_productAddressService.GetById(id));

            return RedirectToAction("Products", "Product");
        }
    }
}

AdminPanel/Controllers/ProductController.cs
using AdminPanel.Models;
using AdminPanel.Repository.Interfaces;
using AdminPanel.Repository.Repository;
using AdminPanel.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace AdminPanel.Controllers
{
    public class ProductController : Controller
    {
      
        private IProductService _productService;
        private ICategoryService _categoryService;
        public ProductController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        public IActionResult Products()
        {
            return View(_productService.GetAll());
        }

        public IActionResult Add() 
        {
            ViewBag.Categories = _categoryService.GetAll();
            return View();
        }

        [HttpPost]
        public IActionResult Add(Product product) 
        { 
            _productService.Add(product);
           
            return RedirectToAction("Products");
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            _productService.Remove(_productService.GetById(id));

            return RedirectToAction("Products");
        }

        public IActionResult Update(int id)
        {
            ViewBag.Categories = _categoryService.GetAll();
            return View(_productService.GetById(id));
        }

        [HttpPost]
        public IActionResult Update(Product product)
        {
            
            _productService.Update(product);

            return RedirectToAction("Products");
        }
    }
}

AdminPanel/Controllers/ProductPropertyController.cs
using AdminPanel.Models;
using AdminPanel.Repository.Interfaces;
using AdminPanel.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace AdminPanel.Controllers
{
    public class ProductPropertyController : Controller
    {
        private IProductPropertyService _productPropertyService;
        private IPropertyRepository _propertyRepository;
        public ProductPropertyController(IProductPropertyService productPropertyService, IPropertyRepository propertyRepository)
        {
            _productPropertyService = productPropertyService;
            _propertyRepository = propertyRepository;
        }

        public IActionResult Add(int productId)
        {
            ViewBag.ProductId = productId;
            ViewBag.Property = _propertyRepository.GetAll();
            return View();
        }

        public IActionResult Delete(int id)
        {
            _productPropertyService.Delete(_productPropertyService.GetById(id));

            return RedirectToAction("Products", "Product");
        }

        [HttpPost]
        public IActionResult Add(ProductProperty productProperty)
        {
           
            _productPropertyService.Add(productProperty);

            return RedirectToAction("Products", "Product");
        }

        public IActionResult Update(int id)
        {
            return View(_productPropertyService.Get(id));
        }

        [HttpPost]
        public IActionResult Update(List<ProductProperty> list)
        {
            _productPropertyService.Update(list);

            return RedirectToAction("Products", "Product");
        }
    }
}

AdminPanel/Views/Product/Add.cshtml
@model Product
@{
    ViewData["Title"] = "Добавление продукта";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<form enctype="multipart/form-data" asp-action="Add" asp-controller="Product" method="post">
    <div class="form-group">
        <label asp-for="Name">Введите имя для продукта</label>
        <input type="text" asp-for="Name" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="PriceIncome">Введите цену продукта при входе</label>
        <input type="text" asp-for="PriceIncome" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="PriceOutCome">Введите цену продукта при выходе</label>
        <input type="text" asp-for="PriceOutCome" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="BarCode">Введите Barcode</label>
        <input type="text" asp-for="BarCode" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="ShortDesc">Введите короткое описание для продукта</label>
        <input type="text" asp-for="ShortDesc" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="LongDesc">Введите описание для продукта</label>
        <input type="text" asp-for="LongDesc" class="form-control">
    </div>
    <div class="form-group">
        <label>Выберите опцию</label>
        <select class="form-select" asp-for="CategoryId">
            <option selected>Выберите опцию</option>
            @foreach (var item in @ViewBag.Categories)
            {
                <option value="@item.Id">@item.Name</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label asp-for="CoverPhoto">Выберите фото</label>
        <div class="custom-file">
           <input asp-for="CoverPhoto" class="custom-file-input">
           <label class="custom-file-label">Выберите файл</label>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Count">Введите количество продукта</label>
        <input type="text" asp-for="Count" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Добавить</button>
</form>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script type="text/javascript">
        $(".custom-file-input").on("change", function ()
        {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

        

AdminPanel/Views/Product/Products.cshtml
@model List<Product>
@{
    ViewData["Title"] = "Продукты";
}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Изображение</th>
            <th scope="col">Название</th>
            <th scope="col">Количество</th>
            <th scope="col">#</th>
            <th scope="col">#</th>
            <th scope="col">#</th>
            <th scope="col">#</th>
        </tr>
    </thead>
    
    <tbody>
        @foreach (var item in Model)
        {
           
            <tr scope="row">
                
                <td><img src="~/products/images/@item.Image" class="test"></td>
                <td>@item.Name</td>
                <td>@item.Count</td>
                <td>
                <form method="post" asp-action="Remove" asp-controller="Product" asp-route-id="@item.Id">
                    <button class="btn btn-primary">Удалить</button>
                </form>
                </td>
                <td>
                <a class="btn btn-primary"asp-action="Update" asp-controller="Product" asp-route-id="@item.Id">Изменить</a>
                </td>
                <td>
                    <a class="btn btn-primary"asp-action="Update" asp-controller="ProductProperty" asp-route-id="@item.Id">Изменить характеристики</a>
                </td>
                <td>
                    <a class="btn btn-primary"asp-action="Add" asp-controller="ProductProperty" asp-route-productId="@item.Id">Добавить характеристики</a>
                </td>
                <td>
                    <a class="btn btn-primary" asp-action="Update" asp-controller="ProductAddress" asp-route-id="@item.Id">Изменить регион</a>
                </td>
            </tr>
           
        }
    </tbody>
</table>

AdminPanel/Views/Product/Update.cshtml
@model Product
@{
    ViewData["Title"] = "Изменение продукта";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<form enctype="multipart/form-data" asp-action="Update" asp-controller="Product" method="post">
    <div class="form-group">
        <label asp-for="Name">Введите имя для продукта</label>
        <input type="text" asp-for="Name" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="PriceIncome">Введите цену продукта при входе</label>
        <input type="text" asp-for="PriceIncome" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="PriceOutCome">Введите цену продукта при выходе</label>
        <input type="text" asp-for="PriceOutCome" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="ShortDesc">Введите короткое описание для продукта</label>
        <input type="text" asp-for="ShortDesc" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="LongDesc">Введите описание для продукта</label>
        <input type="text" asp-for="LongDesc" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="BarCode">Введите BarCode</label>
        <input type="text" asp-for="BarCode" class="form-control">
    </div>
    <div class="form-group">
        <label>Выберите опцию</label>
        <select class="form-select" asp-for="CategoryId">
            <option selected>Выберите опцию</option>
            @foreach (var item in @ViewBag.Categories)
            {
                <option value="@item.Id">@item.Name</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label asp-for="CoverPhoto">Выберите фото</label>
        <div class="custom-file">
            <input asp-for="CoverPhoto" class="custom-file-input">
            <label class="custom-file-label">Выберите файл</label>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Count">Введите количество продукта</label>
        <input type="text" asp-for="Count" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Изменить</button>
</form>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script type="text/javascript">
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}